# Generated by Django 3.2 on 2022-08-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptmodel',
            name='transcript',
            field=models.TextField(),
        ),
    ]
