# Generated by Django 3.2 on 2022-08-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_service', '0002_alter_transcriptmodel_transcript'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcriptmodel',
            name='transcript',
            field=models.TextField(unique=True),
        ),
    ]
